
server:
  port: ${port:8080}
  servlet:
    context-path: /api/v1
  max-http-header-size: 40MB


spring:
  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

error:
  log:
    config:
      filename: error

#??? ?????
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health,info,beans,conditions
        exclude: threaddump, heapdump
  endpoint:
    shutdown:
      enabled: true